baseURL = "https://maxinexinyabi.github.io/XinyaBlog/"
languageCode = 'en-us'
title = "O'Riley42!"
theme = 'hugo-book'

[params]
BookTheme = 'light'

[outputs]
home = ["HTML", "RSS"]
page = ["HTML"]
section = ["HTML", "RSS"]


